GEMINI_API_KEY = "AIzaSyYourRealGeminiKeyHere"
OPENAI_API_KEY = "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"
DEEPSEEK_API_KEY = "sk-4618b3ad85984908a5349399104154c4"
